### ISSUE TITLE
module 'cuckoo_cam' not found for U280

### ISSUE THREAD

**Issue by zzulb** [hpcn-uam/Limago#12]
Hi~ Can you provide cuckoo_cam.dcp for u280, thank you very much! 

My email address cctvlibin@163.com

ERROR: [Synth 8-439] module 'cuckoo_cam' not found [/u280/Limago-master/src/wrapper/alveou280_fns_single_toe_wrapper.v:108]
ERROR: [Synth 8-6156] failed synthesizing module 'alveou280_fns_single_toe_wrapper' [/u280/Limago-master/src/wrapper/alveou280_fns_single_toe_wrapper.v:3]

**Comment by zzulb** [comment]
My vivado is 2019.2

**Comment by mariodruiz** [comment]
Please refer to

https://github.com/hpcn-uam/Limago/issues/3#issuecomment-721904408

The current dcp is valid for U280

**Comment by zzulb** [comment]
The error is shown in the figure below. Is it because it's HBM project ？

![3d8fe59617e07643961ae33d5d9b037](https://user-images.githubusercontent.com/29770636/101317074-bbb02600-3898-11eb-86d3-c5b77858399b.png)
![f7291eac30d28c2e0e59c09cec918bd](https://user-images.githubusercontent.com/29770636/101317090-c074da00-3898-11eb-8351-b2407b15dc36.png)

**Comment by mariodruiz** [comment]
What steps have you taken?
Can you replay these questions? https://github.com/hpcn-uam/Limago/issues/3#issuecomment-721904408

If the file was not cloned with git lfs in the beginning, it is better if you delete the project and regenerate it, after making sure the dcp file is not empty in the repository.

**Comment by zzulb** [comment]
The "cuckoo_cam.dcp" is in \Limago-master\submodules\cuckooCam\

The steps are:
1. make ips;
2. make create_prj_alveou280-fns-single-toe-iperf.

I think it may be caused by different versions of vivado.

**Comment by mariodruiz** [comment]
The issue in Vivado indicate that the file is empty,

What is the output of `ls -la cuckoo_cam.dcp`

**Comment by zzulb** [comment]
The "cuckoo_cam.dcp" is in \Limago-master\submodules\cuckooCam\
![a45d17aee0ec6c2bfd98ad2d9fa104f](https://user-images.githubusercontent.com/29770636/101332133-db067d80-38af-11eb-8961-99fd908823e1.png)

"cuckoo_cam.xdc" is ok！
![ce9c927babf6ae537404ebc484a0ed6](https://user-images.githubusercontent.com/29770636/101332367-27ea5400-38b0-11eb-8bcc-aa2e19bfe2f6.png)

**Comment by mariodruiz** [comment]
The file is empty, the documentation states that you need `git lfs` installed and to clone the repository recursively. At least one of these conditions are not met.

Please look at the correct file size and md5sum:

```sh
ls -la cuckoo_cam.dcp
-rw-rw-r-- 1 mario mario 1084339 Dec  7 12:24 cuckoo_cam.dcp
md5sum cuckoo_cam.dcp
408e62a58bd4af9a65bdfa3866d48ac3  cuckoo_cam.dcp
```

You can either follow the steps to install [git lfs](https://github.com/git-lfs/git-lfs/wiki/Installation) and pull dcp `git lfs pull` or download the file directly from here https://github.com/hpcn-uam/Limago/blob/master/submodules/cuckooCam/cuckoo_cam.dcp

**Comment by zzulb** [comment]
It's ok now, thank you very much！
