### ISSUE TITLE
The cuckoo_cam.dcp is not a valid design checkpoint

### ISSUE THREAD

**Issue by xiaoliang201188** [hpcn-uam/Limago#13]
![image](https://user-images.githubusercontent.com/44012418/104174730-8d96a680-5441-11eb-8622-7209b5b92a0f.png)
I downed the code by .zip file .

**Comment by mariodruiz** [comment]
The cuckoocam is stashed with git LFS, so you may need to download it separately https://github.com/hpcn-uam/Limago/raw/master/submodules/cuckooCam/cuckoo_cam.dcp

**Comment by xiaoliang201188** [comment]
Thanks. It solved in windows.  Howerver it reported err again when I transfered the dcp file by ftp from windows to linux.

**Comment by xiaoliang201188** [comment]
Solved! Thanks.
