### ISSUE TITLE
bitstream generation is not permitted

### ISSUE THREAD

**Issue by Tyux** [hpcn-uam/Limago#17]
When I tried to generate bitstream, i got error like this:

```
[Common 17-69] Command failed: This design contains one or more cells for which bitstream generation is not permitted:
bd_wrapper_i/bd_i/Interfaces/cmac_wrapper_0/inst/cmac_connector_i/cmac_wrapper_i/cmac_0/inst/i_cmac_uplus_0_top (<encrypted cellview>)
If a new IP Core license was added, in order for the new license to be picked up, the current netlist needs to be updated by resetting and re-generating the IP output products before bitstream generation.
```

I tried the operation suggested by  official：
https://www.xilinx.com/support/answers/58758.html
https://www.xilinx.com/support/answers/57264.html

1.Add  ip repository to settings
![2021-03-22 15-10-40屏幕截图](https://user-images.githubusercontent.com/22398165/111952899-cd080000-8b20-11eb-9ffe-83e6f68839b2.png)

2.reset the output products of a block design

But error still, how can i fix this?

**Comment by mariodruiz** [comment]
Hi @Tyux, it seems that you generated the IP with an older Vivado version and are trying to implement the project with a newer Vivado version.

My recommendation is to start from scratch the build, clone repo again, and only use the supported Vivado version, 2018.3.

**Comment by Tyux** [comment]
I changed my license and then issue solved. Thank you @mariodruiz .
