### ISSUE TITLE
the cmac_sync patch process

### ISSUE THREAD

**Issue by luyong6** [hpcn-uam/Limago#5]
When I git clone a new project and run 'make ips' with Vivado 2020.1, 
I met an issue to "patch" three files for submodules/cmac_sync
```
src/cmac_sync/rx_sync.v
src/cmac_sync/tx_sync.v
src/cmac_sync/cmac_0_axi4_lite_user_if.v
```

What is the purpose for that? I found it is a vague step because of two things on `example_cmac.tcl`:
* when generating an example design, it uses vcu118, and doesn't fit for other boards
* LANE_NUM {4} doesn't work in Vivado 2020.1, which requires {4x25}

I couldn't quite understand the three patch files, they seemed to have completely rewritten the three files. 

Would you help have a look?

**Comment by mariodruiz** [comment]
Hi @luyong6, these files are necessary for the cmac_sync as you mentioned. In the first place the files were taken from an example design and contains a Xilinx code, to avoid conflicts, I am generating an example design to grab the files and patch them with a few changes. The process works for Vivado 2018.3, but, I have noticed that it does not work for newer versions.

I do not have much time to have a look, but I will try to do it over the weekend.
