### ISSUE TITLE
failure when creating project

### ISSUE THREAD

**Issue by bournejason** [hpcn-uam/Limago#6]
Hi Mario
I am using the same 2018.3 Vivado build and I successfully finished 'make ups' without any problems.
But when I tried to 'make create_prj_vcu118-fns-single-toe-echo' I encountered such failure:

_INFO: [Device 21-403] Loading part xcvu9p-flga2104-2L-e
xit::create_sub_core: Time (s): cpu = 00:00:18 ; elapsed = 00:00:38 . Memory (MB): peak = 2664.527 ; gain = 970.090 ; free physical = 25091 ; free virtual = 509154
create_bd_cell: Time (s): cpu = 00:00:32 ; elapsed = 00:00:53 . Memory (MB): peak = 2664.527 ; gain = 1046.457 ; free physical = 25066 ; free virtual = 509128
create_bd_cell: Time (s): cpu = 00:00:22 ; elapsed = 00:01:00 . Memory (MB): peak = 2848.832 ; gain = 184.305 ; free physical = 24204 ; free virtual = 508268
**ERROR: [BD 5-216] VLNV <xilinx.com:hls:arp_server:1.0> is not supported for the current part. 
ERROR: [Common 17-39] 'create_bd_cell' failed due to earlier errors.**
    while executing
"create_bd_cell -type ip -vlnv xilinx.com:hls:arp_server:1.0 arp_server_0 "
    (procedure "create_hier_cell_ARP" line 59)
    invoked from within
"create_hier_cell_ARP $hier_obj ARP"
    (procedure "create_hier_cell_interface_0_handler" line 53)
    invoked from within
"create_hier_cell_interface_0_handler [current_bd_instance .] interface_0_handler"
    (procedure "create_root_design" line 72)
    invoked from within
"create_root_design """
    (file "./scripts/vcu118-fns-single-toe-echo/block_design.tcl" line 1886)
    while executing
"source ./scripts/${project_name}/block_design.tcl"
    (file "scripts/common_scripts/create_project.tcl" line 45)
INFO: [Common 17-206] Exiting Vivado at Mon Aug 31 16:49:05 2020...
make: *** [create_prj_vcu118-fns-single-toe-echo] Error 1_

Do you have any clues on the cause of this failure? 
Thanks in advance!

**Comment by mariodruiz** [comment]
Did you solve it?
What was the issue?

**Comment by bournejason** [comment]
> Did you solve it?
> What was the issue?

It was because when doing 'make ips', same ips were generated under both "submodules/fpga-network-stack-core/synthesis_results_noHBM" and "submodules/fpga-network-stack-core/synthesis_results_HBM", which caused some Critical Warnings about duplicated IPs, and in some way finally caused the failure..
I changed makefile locally to only make ips for noHBM device, and the issue was gone.

**Comment by mariodruiz** [comment]
Thank you. I will try to fix that
